'''
first_name="xiaoyuan"
last_name="zhang"
full_name=first_name+""+last_name
print(full_name)
'''
first_name="xiaoyuan"
last_name="zhang"
full_name=first_name+""+last_name
message="hello,"+full_name.title()+"!"
print(message)